name: demo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2021.10.26
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - ld_impl_linux-64=2.36.1
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.21.2
  - openssl=3.0.0
  - pip=21.3.1
  - python=3.8.12
  - python_abi=3.8
  - readline=8.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=60.5.0
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - ansiwrap==0.8.4
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==21.4.0
    - autopep8==1.6.0
    - babel==2.9.1
    - backcall==0.2.0
    - backoff==1.11.1
    - black==21.12b0
    - bleach==4.1.0
    - boto3==1.20.46
    - botocore==1.23.46
    - build==0.7.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.10
    - click==8.0.3
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distro==1.6.0
    - entrypoints==0.3
    - fonttools==4.29.0
    - greenlet==1.1.2
    - humanize==3.13.1
    - idna==3.3
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - ipdb==0.13.9
    - ipykernel==6.7.0
    - ipython==7.31.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isort==5.10.1
    - jedi==0.18.1
    - jinja2==3.0.3
    - jmespath==0.10.0
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyter-server==1.13.4
    - jupyterlab==3.2.8
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - jupyterlab-widgets==1.0.2
    - jupytext==1.13.6
    - kiwisolver==1.3.2
    - markdown-it-py==1.1.0
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mdit-py-plugins==0.3.0
    - mistune==0.8.4
    - monotonic==1.6
    - mypy-extensions==0.4.3
    - nbclassic==0.3.5
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - notebook==6.4.8
    - numpy==1.22.1
    - packaging==21.3
    - pandas==1.4.0
    - pandocfilters==1.5.0
    - papermill==2.3.4
    - parso==0.8.3
    - pathlib==1.0.1
    - pathspec==0.9.0
    - pep517==0.12.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.0
    - platformdirs==2.4.1
    - ploomber==0.14.7
    - ploomber-scaffold==0.2.4
    - pluggy==1.0.0
    - posthog==1.4.5
    - prometheus-client==0.13.0
    - prompt-toolkit==3.0.26
    - ptyprocess==0.7.0
    - py==1.11.0
    - pycodestyle==2.8.0
    - pycparser==2.21
    - pydantic==1.9.0
    - pyflakes==2.4.0
    - pygments==2.11.2
    - pygraphviz==1.8
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.2.2
    - qtpy==2.0.0
    - requests==2.27.1
    - s3transfer==0.5.0
    - send2trash==1.8.0
    - sklearn-evaluation==0.5.7
    - sniffio==1.2.0
    - soopervisor==0.6.1
    - soorgeon==0.0.12
    - sqlalchemy==1.4.31
    - sqlparse==0.4.2
    - tabulate==0.8.9
    - tenacity==8.0.1
    - terminado==0.13.1
    - testpath==0.5.0
    - textwrap3==0.9.2
    - threadpoolctl==3.0.0
    - toml==0.10.2
    - tomli==1.2.3
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.1
    - typing-extensions==4.0.1
    - urllib3==1.26.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - widgetsnbextension==3.5.2
    - zipp==3.7.0
